# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_name', models.CharField(max_length=100)),
                ('admin_id', models.IntegerField()),
                ('pub_date', models.DateTimeField(verbose_name='date publish')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('message', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date publish')),
                ('board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.Board')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date publish')),
            ],
        ),
    ]
